name: 'Set up conda environment'
description: 'Set up conda environment using a requirements file'
inputs:
  channels:
    description: 'Conda channels'
    required: true
  env-file:
    description: 'URL with an environment file'
    required: true
  activate-environment:
    description: 'See conda-incubator/setup-miniconda, activate-environment for description'
    required: false
    default: 'test'

runs:
  using: "composite"
  steps:
    - name: Set up env
      shell: bash -l {0}
      run: |
        echo "CONDA=$HOME/miniconda3" >> $GITHUB_ENV
        echo "CONDA_NUMBER_CHANNEL_NOTICES=0" >> $GITHUB_ENV

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: false
        channels: ${{ inputs.channels }}
        channel-priority: strict
        activate-environment: ${{ inputs.activate-environment }}

    - name: Install requirements
      shell: bash -l {0}
      run: |
        curl -n -o requirements.txt ${{ inputs.env-file }}
        mamba install --file requirements.txt
